.ts:
  techstack:
    - typescript
    - jest
  context: |-
    Write for each exported function a unit test. Wrap test groups in 'describe' blocks.
  examples:
    - name: agents file
      code: src/agents/agents.ts
      tests: src/agents/agents.test.ts