.ts:
  techstack:
    - typescript
    - jest
  context: |-
    Write for each exported function a unit test. Wrap test groups in 'describe' blocks.
  examples:
    - name: openai file
      code: src/openai.ts
      tests: src/openai.test.ts